DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS files;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE files (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  user_id INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_name TEXT,
  transcription TEXT,
  FOREIGN KEY (user_id) REFERENCES user (id)
);