DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE files (
  id INTEGER PRIMARY KEY UNIQUE AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  hashed_filename TEXT NOT NULL,
  file_data BLOB NOT NULL,
  transcription TEXT,
  FOREIGN KEY (user_id) REFERENCES user (id)
)

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
